// ShieldAI — Unified Notification Dispatcher (Phase 6)
// Sends alerts via Slack and/or creates GitHub issues for critical findings

Deno.serve(async (req) => {
  const body = await req.json().catch(() => ({}));
  const { finding, channel = "slack", severity_threshold = "high" } = body;

  const SLACK_WEBHOOK = Deno.env.get("SLACK_WEBHOOK_URL") || "";
  const GITHUB_TOKEN = Deno.env.get("GITHUB_TOKEN") || "";
  const GITHUB_REPO = Deno.env.get("GITHUB_REPO") || ""; // format: owner/repo

  const severityOrder: Record<string, number> = { critical: 4, high: 3, medium: 2, low: 1, info: 0 };
  const thresholdLevel = severityOrder[severity_threshold] || 3;
  const findingSeverityLevel = severityOrder[finding?.severity] || 0;

  if (findingSeverityLevel < thresholdLevel) {
    return Response.json({ success: true, skipped: true, reason: `Severity ${finding?.severity} below threshold ${severity_threshold}` });
  }

  const results: any = {};
  const severityEmoji: Record<string, string> = { critical: "🔴", high: "🟠", medium: "🟡", low: "🟢" };
  const emoji = severityEmoji[finding?.severity] || "⚪";

  // Send to Slack
  if (SLACK_WEBHOOK && (channel === "slack" || channel === "all")) {
    try {
      const slackPayload = {
        blocks: [
          { type: "header", text: { type: "plain_text", text: `${emoji} ShieldAI Security Alert — ${finding?.severity?.toUpperCase()}` } },
          { type: "section", fields: [
            { type: "mrkdwn", text: `*Finding:*\n${finding?.title}` },
            { type: "mrkdwn", text: `*Pillar:*\n${finding?.pillar || "Unknown"}` },
            { type: "mrkdwn", text: `*Resource:*\n\`${finding?.resource || finding?.endpoint || "N/A"}\`` },
            { type: "mrkdwn", text: `*Detected:*\n${new Date(finding?.detected_at || Date.now()).toLocaleString()}` },
          ]},
          { type: "section", text: { type: "mrkdwn", text: `*Description:*\n${finding?.description}` } },
          { type: "section", text: { type: "mrkdwn", text: `*Remediation:*\n${finding?.remediation}` } },
          { type: "divider" },
          { type: "section", text: { type: "mrkdwn", text: "View in ShieldAI: <https://shieldai.app|Open Dashboard>" } }
        ]
      };
      const slackRes = await fetch(SLACK_WEBHOOK, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(slackPayload) });
      results.slack = { sent: slackRes.ok, status: slackRes.status };
    } catch (e: any) {
      results.slack = { sent: false, error: e.message };
    }
  }

  // Create GitHub Issue
  if (GITHUB_TOKEN && GITHUB_REPO && (channel === "github" || channel === "all")) {
    try {
      const labels = ["security", finding?.severity, finding?.pillar].filter(Boolean);
      const issueBody = `## ${emoji} Security Finding — ${finding?.severity?.toUpperCase()}\n\n` +
        `**Title:** ${finding?.title}\n` +
        `**Pillar:** ${finding?.pillar || "Unknown"}\n` +
        `**Resource:** \`${finding?.resource || finding?.endpoint || "N/A"}\`\n` +
        `**Detected:** ${finding?.detected_at || new Date().toISOString()}\n\n` +
        `### Description\n${finding?.description}\n\n` +
        `### Remediation\n\`\`\`\n${finding?.remediation}\n\`\`\`\n\n` +
        `${finding?.cve_id ? `**CVE:** [${finding.cve_id}](https://nvd.nist.gov/vuln/detail/${finding.cve_id})\n` : ""}` +
        `${finding?.cvss_score ? `**CVSS Score:** ${finding.cvss_score}\n` : ""}` +
        `\n---\n*Auto-generated by ShieldAI Security Platform*`;

      const ghRes = await fetch(`https://api.github.com/repos/${GITHUB_REPO}/issues`, {
        method: "POST",
        headers: { Authorization: `Bearer ${GITHUB_TOKEN}`, "Content-Type": "application/json", "Accept": "application/vnd.github.v3+json" },
        body: JSON.stringify({ title: `[ShieldAI] ${emoji} ${finding?.title}`, body: issueBody, labels })
      });
      const ghData = await ghRes.json();
      results.github = { sent: ghRes.ok, issue_url: ghData.html_url, number: ghData.number };
    } catch (e: any) {
      results.github = { sent: false, error: e.message };
    }
  }

  return Response.json({ success: true, finding_title: finding?.title, severity: finding?.severity, notifications_sent: results });
});
