export default async function handler(req: Request): Promise<Response> {
  const pages = [
    ['/', 'Home'],
    ['/how-it-works', 'How It Works'],
    ['https://primeendorsement.com/api/functions/peaStatusPage', 'Track Application'],
    ['/verify-endorsement', 'Verify Certificate'],
    ['/member-login', 'Member Login'],
  ];

  const hiddenPrefixes = [
    '/pea-admin', '/admin-login', '/admin-dashboard', '/admin/',
    '/supreme-admin', '/premium-admin', '/applicant-portal',
    '/cofounder-dashboard', '/member-dashboard', '/portal', '/reviewer',
    '/secure-admin-gateway',
  ];

  const pagesJson = JSON.stringify(pages);
  const hiddenJson = JSON.stringify(hiddenPrefixes);
  const gold = '#C9A84C';
  const bg = 'rgba(10,14,26,0.97)';
  const navH = 56;

  const js = [
    '(function(){',
    '"use strict";',
    'var PAGES=' + pagesJson + ';',
    'var HIDDEN=' + hiddenJson + ';',
    'var GOLD="' + gold + '";',
    'var GOLD25="rgba(201,168,76,0.25)";',
    'var GOLD20="rgba(201,168,76,0.2)";',
    'var BG="' + bg + '";',
    'var NAV_H=' + navH + ';',
    'var ID="__pea_bnav__";',
    '',
    'function idx(){',
    '  var p=window.location.pathname.replace(/\\/+$/,"");',
    '  if(!p)p="/";',
    '  for(var i=0;i<PAGES.length;i++){',
    '    var pg=PAGES[i][0];',
    '    // match full URL or path',
    '    if(pg===p)return i;',
    '    try{var u=new URL(pg);if(u.pathname===p)return i;}catch(e){}',
    '  }',
    '  return -1;',
    '}',
    '',
    'function hide(){',
    '  var p=window.location.pathname;',
    '  for(var i=0;i<HIDDEN.length;i++){if(p.indexOf(HIDDEN[i])===0)return true;}',
    '  return false;',
    '}',
    '',
    '// Smart navigation: full URL → location.href, path → pushState',
    'function go(path){',
    '  if(path.indexOf("http://")===0||path.indexOf("https://")===0){',
    '    window.location.href=path;',
    '    return;',
    '  }',
    '  if(window.history&&window.history.pushState){',
    '    window.history.pushState(null,"",path);',
    '    window.dispatchEvent(new PopStateEvent("popstate"));',
    '  } else { window.location.href=path; }',
    '}',
    '',
    'function render(){',
    '  var old=document.getElementById(ID);',
    '  if(old)old.remove();',
    '  if(hide())return;',
    '  var i=idx();',
    '  if(i===-1)return;',
    '  var canB=i>0, canF=i<PAGES.length-1;',
    '  var cur=PAGES[i];',
    '',
    '  var dots="";',
    '  for(var d=0;d<PAGES.length;d++){',
    '    var dw=d===i?"18px":"5px";',
    '    var dc=d===i?GOLD:GOLD25;',
    '    dots+=\'<div data-dot="\'+d+\'" style="width:\'+dw+\';height:5px;border-radius:3px;background:\'+dc+\';cursor:pointer;transition:all 0.3s;flex-shrink:0"></div>\';',
    '  }',
    '',
    '  var nav=document.createElement("div");',
    '  nav.id=ID;',
    '  nav.setAttribute("style","position:fixed;bottom:0;left:0;right:0;z-index:99999;height:"+NAV_H+"px;display:flex;align-items:center;justify-content:space-between;padding:0 20px;background:"+BG+";backdrop-filter:blur(14px);-webkit-backdrop-filter:blur(14px);border-top:1px solid "+GOLD20+";box-shadow:0 -4px 24px rgba(0,0,0,0.5);font-family:-apple-system,BlinkMacSystemFont,Inter,sans-serif;box-sizing:border-box");',
    '',
    '  var bStyle="background:transparent;border:none;cursor:"+(canB?"pointer":"default")+";color:"+(canB?GOLD:GOLD25)+";font-size:12px;font-weight:600;letter-spacing:1px;display:flex;align-items:center;gap:6px;padding:8px 10px;border-radius:5px;min-width:100px;white-space:nowrap";',
    '  var fStyle="background:transparent;border:none;cursor:"+(canF?"pointer":"default")+";color:"+(canF?GOLD:GOLD25)+";font-size:12px;font-weight:600;letter-spacing:1px;display:flex;align-items:center;gap:6px;padding:8px 10px;border-radius:5px;min-width:100px;white-space:nowrap;justify-content:flex-end";',
    '',
    '  var bHTML=canB?"<span style=\'font-size:15px\'>&larr;</span><span>"+PAGES[i-1][1]+"</span>":"<span style=\'opacity:0\'>x</span>";',
    '  var fHTML=canF?"<span>"+PAGES[i+1][1]+"</span><span style=\'font-size:15px\'>&rarr;</span>":"<span style=\'opacity:0\'>x</span>";',
    '',
    '  nav.innerHTML=',
    '    \'<button id="__pea_b__" style="\'+bStyle+\'">\'+bHTML+\'</button>\'',
    '   +\'<div style="display:flex;flex-direction:column;align-items:center;gap:5px;flex:1;padding:0 8px">\'',
    '   +\'<div style="color:\'+GOLD+\';font-size:10px;letter-spacing:3px;text-transform:uppercase;font-weight:600;white-space:nowrap">\'+(i+1)+\' / \'+PAGES.length+\' &nbsp;&middot;&nbsp; \'+cur[1]+\'</div>\'',
    '   +\'<div style="display:flex;gap:5px;align-items:center">\'+dots+\'</div>\'',
    '   +\'</div>\'',
    '   +\'<button id="__pea_f__" style="\'+fStyle+\'">\'+fHTML+\'</button>\';',
    '',
    '  if(canB)nav.querySelector("#__pea_b__").setAttribute("data-nav",PAGES[i-1][0]);',
    '  if(canF)nav.querySelector("#__pea_f__").setAttribute("data-nav",PAGES[i+1][0]);',
    '',
    '  document.body.appendChild(nav);',
    '',
    '  var main=document.querySelector("main")||document.querySelector("#root")||document.body;',
    '  var pb=parseInt(window.getComputedStyle(main).paddingBottom||"0",10);',
    '  if(pb<NAV_H+8)main.style.paddingBottom=(NAV_H+8)+"px";',
    '',
    '  nav.addEventListener("click",function(e){',
    '    var el=e.target;',
    '    for(var n=0;n<10;n++){',
    '      if(!el||el===nav)break;',
    '      var nav_attr=el.getAttribute&&el.getAttribute("data-nav");',
    '      if(nav_attr){go(nav_attr);return;}',
    '      var dot_attr=el.getAttribute&&el.getAttribute("data-dot");',
    '      if(dot_attr!==null&&dot_attr!==undefined&&dot_attr!==""){go(PAGES[parseInt(dot_attr,10)][0]);return;}',
    '      el=el.parentElement;',
    '    }',
    '  });',
    '',
    '  [nav.querySelector("#__pea_b__"),nav.querySelector("#__pea_f__")].forEach(function(btn){',
    '    if(!btn||!btn.getAttribute("data-nav"))return;',
    '    btn.addEventListener("mouseenter",function(){btn.style.background="rgba(201,168,76,0.08)";});',
    '    btn.addEventListener("mouseleave",function(){btn.style.background="transparent";});',
    '  });',
    '}',
    '',
    'function init(){',
    '  if(document.readyState==="loading"){document.addEventListener("DOMContentLoaded",render);}',
    '  else{render();}',
    '  var _ps=window.history.pushState.bind(window.history);',
    '  window.history.pushState=function(){_ps.apply(window.history,arguments);setTimeout(render,100);};',
    '  window.addEventListener("popstate",function(){setTimeout(render,100);});',
    '}',
    '',
    'init();',
    '})();',
  ].join('\n');

  return new Response(js, {
    headers: {
      'Content-Type': 'application/javascript; charset=utf-8',
      'Cache-Control': 'public, max-age=300',
      'Access-Control-Allow-Origin': '*',
    },
  });
}
